// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RookEcomShop.Persistence;

#nullable disable

namespace RookEcomShop.Persistence.Migrations
{
    [DbContext(typeof(RookEcomShopDbContext))]
    partial class RookEcomShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.CartDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartDetails", (string)null);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Beauty & Personal Care"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Health & Wellness"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jewelry & Accessories"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Baby & Kids"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Grocery & Gourmet"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Name = "Tablets"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Name = "Appliances"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Name = "Decor"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Name = "Non-Fiction"
                        });
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Item 4539",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Item 7930",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Item 1277",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Item 1042",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Thing 6961",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Item 9327",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Gadget 7204",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Device 4903",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Item 1015",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Gadget 1720",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Device 5926",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Device 4253",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Widget 8205",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Device 6948",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Gadget 7468",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Thing 8413",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Gadget 8276",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Gadget 1427",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Gadget 5237",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Device 6606",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Gadget 2124",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Widget 6517",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Widget 6734",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Thing 8679",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Gadget 2225",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Item 6522",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Device 8171",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Thing 4368",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Item 2357",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Widget 5993",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Device 6058",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Gadget 2337",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Thing 2265",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Item 7520",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Item 8436",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Item 9028",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Thing 3262",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Item 9421",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Device 9079",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Device 7818",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Thing 3719",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Thing 9350",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Item 7546",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Gadget 4613",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Widget 1933",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Widget 7839",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Widget 2311",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Item 9335",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Widget 2829",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Widget 3181",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Item 2871",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Item 8402",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Device 2661",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Device 6856",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Item 5094",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Thing 9974",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Gadget 8139",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Gadget 9325",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Widget 5224",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Gadget 6900",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Device 3267",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Device 3131",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Device 8534",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Thing 7668",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Device 9859",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Item 2897",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Device 7264",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Device 1712",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Widget 5677",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Widget 3460",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Widget 7978",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Widget 2012",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Item 2497",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Thing 7745",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Item 2061",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Device 7310",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Item 9495",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Item 2018",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Gadget 2607",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Item 3225",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Gadget 3291",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Thing 8158",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Item 5555",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Item 5354",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Item 2335",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Item 1873",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Gadget 1236",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Device 7454",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Thing 9604",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Item 3553",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Thing 7538",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Limited edition",
                            Name = "Item 6445",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Device 6316",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Gadget 6375",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Gadget 3998",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Popular",
                            Name = "Gadget 2940",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Brand new",
                            Name = "Gadget 5171",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Thing 2618",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "High quality",
                            Name = "Device 4192",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            Description = "Best seller",
                            Name = "Item 6191",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 27, 12, 12, 20, 60, DateTimeKind.Local).AddTicks(4545),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.CartDetail", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("CartDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Category", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Category", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Order", "Order")
                        .WithOne("PaymentTransaction")
                        .HasForeignKey("RookEcomShop.Domain.Entities.PaymentTransaction", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Product", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Review", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartDetails");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
