// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RookEcomShop.Infrastructure.Persistence;

#nullable disable

namespace RookEcomShop.Infrastructure.Migrations
{
    [DbContext(typeof(RookEcomShopDbContext))]
    [Migration("20240524105257_DeleteProductClientCasecadeCartDetails")]
    partial class DeleteProductClientCasecadeCartDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.CartDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartDetails", (string)null);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Beauty & Personal Care"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Health & Wellness"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jewelry & Accessories"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Baby & Kids"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Grocery & Gourmet"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Name = "Tablets"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Name = "Appliances"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Name = "Decor"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Name = "Non-Fiction"
                        });
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Gadget 6019",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Widget 4360",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Gadget 6199",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Item 6714",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Device 6662",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Widget 4151",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Gadget 3693",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Widget 5517",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Device 6089",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Gadget 3817",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Device 1209",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Gadget 1675",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Device 5607",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Widget 9946",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Gadget 9687",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Widget 4452",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Thing 9731",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Widget 3681",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Device 6090",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Item 2365",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Item 4665",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Gadget 4676",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Item 7892",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Device 2314",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Thing 3186",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Thing 9894",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Widget 3788",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Thing 3809",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Item 2058",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Widget 5678",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Gadget 5302",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Widget 7701",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Thing 8745",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Device 6383",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Widget 3399",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Gadget 7809",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Item 2894",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Gadget 8348",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Widget 5470",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Thing 5430",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Widget 2155",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Gadget 7291",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Device 3916",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Gadget 2029",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Device 1320",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Thing 3349",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Item 1489",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Device 8902",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Widget 2963",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Gadget 4306",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Thing 1432",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Item 5880",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Widget 1130",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Thing 7123",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Gadget 3201",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Device 8991",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Item 1940",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Device 4604",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Item 6343",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Widget 6983",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Widget 3403",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Gadget 1178",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Item 8407",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Device 6741",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Gadget 9705",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Gadget 9567",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Item 4996",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Widget 3150",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Thing 3911",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Gadget 7879",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Device 6893",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Item 5261",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Thing 1041",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Widget 4875",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Item 4189",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Widget 5533",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Thing 9422",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Widget 5017",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Widget 2650",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Thing 5554",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Thing 4825",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Device 1983",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Device 5355",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Widget 4257",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Device 2318",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Widget 7480",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Device 3100",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Item 7619",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Gadget 8743",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Widget 5872",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Widget 9820",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Widget 6662",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Thing 4685",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Limited edition",
                            Name = "Gadget 1824",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Widget 6965",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Device 3870",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "High quality",
                            Name = "Device 7066",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Best seller",
                            Name = "Thing 3421",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Popular",
                            Name = "Thing 4324",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            Description = "Brand new",
                            Name = "Item 6794",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 24, 17, 52, 56, 856, DateTimeKind.Local).AddTicks(6648),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvartarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Cart", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("RookEcomShop.Domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.CartDetail", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("CartDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Category", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Category", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Order", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.PaymentMethod", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", "User")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Order", "Order")
                        .WithOne("PaymentTransaction")
                        .HasForeignKey("RookEcomShop.Domain.Entities.PaymentTransaction", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Product", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Review", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartDetails");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("PaymentMethods");

                    b.Navigation("Products");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
