// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RookEcomShop.Infrastructure.Persistence;

#nullable disable

namespace RookEcomShop.Infrastructure.Migrations
{
    [DbContext(typeof(RookEcomShopDbContext))]
    [Migration("20240522090349_DeleteCartOnCasCade")]
    partial class DeleteCartOnCasCade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.CartDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartDetails", (string)null);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Beauty & Personal Care"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Health & Wellness"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jewelry & Accessories"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Baby & Kids"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Grocery & Gourmet"
                        });
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Gadget 6519",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Item 7147",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Widget 8142",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Popular",
                            Name = "Gadget 6641",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Gadget 5805",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Device 5473",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Widget 5692",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Device 8425",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Widget 5324",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Item 2595",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Gadget 1014",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Thing 3551",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Item 4222",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Device 3657",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Popular",
                            Name = "Thing 9526",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Popular",
                            Name = "Item 4400",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Gadget 2281",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Gadget 7595",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Item 9490",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Item 6682",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Thing 5427",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Thing 3549",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Gadget 7436",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Item 9274",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Device 2379",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Widget 1121",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Item 6370",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Thing 8444",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Gadget 6911",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Popular",
                            Name = "Widget 4839",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Gadget 6011",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Item 3787",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Widget 4189",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Thing 8051",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Thing 6459",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Gadget 4362",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Thing 8691",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Thing 9818",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Device 5513",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Device 5079",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Thing 5069",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Popular",
                            Name = "Widget 6143",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Thing 7102",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Item 1222",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Device 6606",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Device 4629",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Item 6227",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Popular",
                            Name = "Thing 3522",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Popular",
                            Name = "Gadget 8713",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Item 5916",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Thing 7958",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Item 1957",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Item 3411",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Device 3778",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Widget 3489",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Popular",
                            Name = "Gadget 7197",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Device 1308",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Widget 6426",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Widget 9383",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Widget 5166",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Widget 6997",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Popular",
                            Name = "Gadget 5353",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Item 1526",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Device 6162",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Item 7768",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Thing 6381",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Thing 9705",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Item 8941",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Widget 3006",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Item 2560",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Thing 4318",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Popular",
                            Name = "Gadget 2229",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Thing 9238",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Item 9793",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Popular",
                            Name = "Item 1319",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Thing 8277",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Gadget 6798",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Item 8820",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Device 4440",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Thing 9130",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Popular",
                            Name = "Device 4956",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Gadget 9430",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Widget 7161",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Thing 8947",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Thing 6996",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Thing 5617",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Popular",
                            Name = "Widget 2175",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Thing 8144",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Best seller",
                            Name = "Thing 6186",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Item 3093",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Item 2297",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Popular",
                            Name = "Device 8465",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Item 7358",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Thing 3719",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Device 1020",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Popular",
                            Name = "Gadget 5738",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Limited edition",
                            Name = "Gadget 7928",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Thing 9293",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "Brand new",
                            Name = "Thing 8062",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            Description = "High quality",
                            Name = "Item 7747",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 22, 16, 3, 46, 744, DateTimeKind.Local).AddTicks(5813),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvartarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Cart", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("RookEcomShop.Domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.CartDetail", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("CartDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Category", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Category", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Order", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.PaymentMethod", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", "User")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Order", "Order")
                        .WithOne("PaymentTransaction")
                        .HasForeignKey("RookEcomShop.Domain.Entities.PaymentTransaction", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Product", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Review", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartDetails");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("PaymentMethods");

                    b.Navigation("Products");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
