// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RookEcomShop.Infrastructure.Persistence;

#nullable disable

namespace RookEcomShop.Infrastructure.Migrations
{
    [DbContext(typeof(RookEcomShopDbContext))]
    [Migration("20240519094651_DataSeeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.CartDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartDetails", (string)null);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Beauty & Personal Care"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Health & Wellness"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jewelry & Accessories"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Baby & Kids"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Grocery & Gourmet"
                        });
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Thing 6648",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Widget 5500",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Device 2523",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Device 9301",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Device 1348",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Item 2601",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Gadget 3794",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Widget 6745",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Widget 8858",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Item 5631",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Thing 9782",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Thing 7725",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Thing 4473",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Item 3408",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Item 1616",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Item 8358",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Thing 7846",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Thing 8825",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Item 1849",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Item 3997",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Item 2487",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Device 4115",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Item 8958",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Device 6346",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Item 3463",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Device 1518",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Widget 8840",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Gadget 9894",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Thing 2414",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Thing 8058",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Device 1251",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Gadget 9801",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Widget 9023",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Device 9722",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Device 2563",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Gadget 9524",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Thing 5993",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Thing 5041",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Gadget 3512",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Device 5270",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Device 4581",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Widget 3182",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Widget 2332",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Device 3590",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Widget 3888",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Item 7824",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Thing 4106",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Gadget 9461",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Device 4830",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Item 3219",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Thing 2457",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Widget 2553",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Item 2679",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Gadget 9107",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Device 2880",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Widget 7673",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Item 4211",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Widget 3345",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Thing 8433",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Item 2371",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Device 7732",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Widget 3266",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Thing 3902",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Device 6895",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Thing 1154",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Item 2976",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Device 2256",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Gadget 5245",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Thing 4085",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Thing 6138",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Widget 7661",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Widget 2355",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Item 1935",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Device 1033",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Item 4708",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Widget 3152",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Device 5381",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Gadget 4793",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Gadget 6093",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Thing 3499",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Device 9616",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Item 9721",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Thing 9424",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Thing 5528",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Thing 4052",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Widget 8456",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Device 9825",
                            Price = 149.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Device 2031",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Widget 6355",
                            Price = 19.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Gadget 1454",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Brand new",
                            Name = "Item 8672",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Widget 7024",
                            Price = 99.99m,
                            Status = 1,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Thing 4960",
                            Price = 29.99m,
                            Status = 1,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 3, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Thing 2862",
                            Price = 49.99m,
                            Status = 0,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Device 8024",
                            Price = 99.99m,
                            Status = 0,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "High quality",
                            Name = "Device 7878",
                            Price = 29.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Device 6136",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Limited edition",
                            Name = "Widget 9115",
                            Price = 149.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Best seller",
                            Name = "Gadget 1858",
                            Price = 49.99m,
                            Status = 1,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2024, 4, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            Description = "Popular",
                            Name = "Widget 9593",
                            Price = 19.99m,
                            Status = 0,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2024, 2, 19, 16, 46, 50, 652, DateTimeKind.Local).AddTicks(5583),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvartarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Cart", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("RookEcomShop.Domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.CartDetail", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("CartId")
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("CartDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Category", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Category", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Order", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.PaymentMethod", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.User", "User")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Order", "Order")
                        .WithOne("PaymentTransaction")
                        .HasForeignKey("RookEcomShop.Domain.Entities.PaymentTransaction", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Product", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Review", b =>
                {
                    b.HasOne("RookEcomShop.Domain.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RookEcomShop.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartDetails");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("RookEcomShop.Domain.Entities.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("PaymentMethods");

                    b.Navigation("Products");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
