name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        dotnet-version: [8.0.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (React)
        run: npm install
        working-directory: ./rookecomshop-admin

      - name: Build React app
        run: npm run build
        working-directory: ./rookecomshop-admin

      # - name: Run React tests
      #   run: npm test
      #   working-directory: ./rookecomshop-admin

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies (.NET)
        run: dotnet restore ./

      - name: Build .NET API
        run: dotnet build --configuration Release ./

      - name: Run .NET tests
        run: dotnet test ./
